language: ruby

services:
  - redis-server

os:
  - linux
  - osx

before_install:
  - sudo apt-get install graphicsmagick
  - sudo apt-get install libgmp3-dev || brew install gmp
  - npm install -g npm@2.4
  - node --version
  - npm --version
  - npm config set spin false

script:
  - npm i
  - sleep 30
  - curl 127.0.0.1:3030
  - curl 127.0.0.1:9000
  - curl 127.0.0.1:9001
  - curl 127.0.0.1:8080
  - curl 127.0.0.1:1111
  - curl 127.0.0.1:1112
  - curl 127.0.0.1:5050
  - curl 127.0.0.1:5000
  - curl 127.0.0.1:10137
