language: ruby

services:
  - redis-server

os:
  - linux
  - osx

before_install:
  - sudo apt-get install libgmp3-dev || brew install gmp
  - node --version
  - npm config set spin false

script:
  - npm i
